package tj.khujand.solana.trading.bot.core.strategy

import tj.khujand.solana.trading.bot.data.db.Strategy as StrategyRow

/** Маппер строки БД → типизированный конфиг (аналог StrategyMapper в MRX). */
fun StrategyRow.toStrategyConfig(): StrategyConfig = StrategyConfig(
    id = id,
    name = name,
    type = type,
    isActive = is_active == 1L,
    timeframe = timeframe,
    positionSize = position_size,
    maxPositions = max_positions.toInt(),
    slippagePercent = slippage_percent,
    priorityFeeLamports = priority_fee_lamports,
    stopLossPercent = stop_loss_percent,
    takeProfitPercent = take_profit_percent,
    trailingStopEnabled = trailing_stop == 1L,
    trailingStopPercent = trailing_stop_percent,
    trailingActivationPercent = trailing_activation_percent,
    breakEvenEnabled = break_even_enabled == 1L,
    breakEvenTriggerPercent = break_even_trigger_percent,
    breakEvenOffsetPercent = break_even_offset_percent,
    partialTpEnabled = partial_tp_enabled == 1L,
    tp1Percent = tp1_percent,
    tp1ClosePercent = tp1_close_percent,
    tp2Percent = tp2_percent,
    tp2ClosePercent = tp2_close_percent,
    timeStopMinutes = time_stop_minutes.toInt(),
    liquidityExitDropPercent = liquidity_exit_drop_percent,
    maxDailyLoss = max_daily_loss,
    maxDrawdown = max_drawdown,
    cooldownSeconds = cooldown_seconds.toInt(),
    minLiquidityUsd = min_liquidity_usd,
    minMarketCap = min_market_cap,
    maxMarketCap = max_market_cap,
    minTokenAgeMinutes = min_token_age_minutes,
    maxTokenAgeMinutes = max_token_age_minutes,
    minVolumeH1Usd = min_volume_h1_usd,
    minBuySellRatio = min_buy_sell_ratio,
    rugcheckEnabled = rugcheck_enabled == 1L,
    rugcheckMaxScore = rugcheck_max_score.toInt(),
    rangeFilterEnabled = range_filter_enabled == 1L,
    rangeMaxEntryPct = range_max_entry_pct,
    rangeLookbackBars = range_lookback_bars.toInt(),
    rsiPeriod = rsi_period.toInt(),
    rsiOverbought = rsi_overbought,
    rsiOversold = rsi_oversold,
    emaFast = ema_fast.toInt(),
    emaSlow = ema_slow.toInt(),
    atrPeriod = atr_period.toInt(),
    volumeThreshold = volume_threshold,
    darsHigherTf = dars_higher_tf,
    darsCandleLimit = dars_candle_limit.toInt(),
    darsSwingPivotPct = dars_swing_pivot_pct,
    darsRequireHtfTrend = dars_require_htf_trend == 1L,
    darsDominanceRatio = dars_dominance_ratio,
    darsMinCorrectionLenPct = dars_min_correction_len_pct,
    darsRejectAtResistance = dars_reject_at_resistance == 1L,
    darsResistanceProximityPct = dars_resistance_proximity_pct,
    darsMinLegs = dars_min_legs.toInt(),
    darsUseImpulseCorrection = dars_use_impulse_correction == 1L,
    darsUseTrendLevels = dars_use_trend_levels == 1L,
    darsUseFalseBreakout = dars_use_false_breakout == 1L,
    darsUseTriangle = dars_use_triangle == 1L,
)
